### ISSUE TITLE
How could I add more languages?

### ISSUE THREAD

**Issue by chuancho22** [lbgm/vue-pro-calendar#25]
Hello, I love how the calendar works, great job!
The trouble is that I would like to have it in Spanish, how could I do that in my Vue 3 project? 
Once I have the translations done, is it something that could be added in the project, so everyone have it? (I'm kind of new to Open-Source git, and don't know how to contribute, hehe)

Thanks for everything!

**Comment by lbgm** [comment]
Hello, glad to hear you !

the calendar uses i18n to translate. To add more languages you can fork repository locally or contribute.

- Translations root: `src/locales`;
- create translation file like `calendar.es.json`

And that's all.

Thanks !!!

**Comment by lbgm** [comment]
Click on fork according to image. Then you will have a copy of the project on your GitHub profile. Finally work with the copy.
![image](https://github.com/lbgm/vue-pro-calendar/assets/92580505/11bedf96-67a0-425f-8bc7-a92cf56e62e4)

**Comment by chuancho22** [comment]
Oh now I see it, thanks a lot!! I will do the PR in a moment so you can check it. 

Thanks! 😄
