### ISSUE TITLE
Add button "Today"

### ISSUE THREAD

**Issue by escalus-95** [lbgm/vue-pro-calendar#36]
After click on Today button we should return view to current day.
The best position of that button before navigation arrow.
![image](https://github.com/lbgm/vue-pro-calendar/assets/147252273/71839bf5-6447-41cf-8184-e46f75185b1b)

**Comment by lbgm** [comment]
hi @escalus-95, you suggest to add "today" button on this version right ? or what "Today button" do you talk about ?
