### ISSUE TITLE
FirstDayOfWeek

### ISSUE THREAD

**Issue by Jimbow-cl** [lbgm/vue-pro-calendar#38]
Hello!,

I try to start the calendar, at Monday, but I think It's impossible.. :)

I believe it would be incredibly helpful for users like me if the library could include a property like `firstDayOfWeek: 1` that allows us to customize the starting day of the week.

Thanks a lot 👍🏻  :D

**Comment by lbgm** [comment]
Hi @Jimbow-cl

got it !

**Comment by lbgm** [comment]
0: Sunday
1: Monday
