### ISSUE TITLE
The problem of styles

### ISSUE THREAD

**Issue by man0so1** [lbgm/vue-pro-calendar#46]
My site uses one font for the text, but if you go to the calendar page, then the font that is used for the calendar is used absolutely for the entire site. Out of desperation, I even tried:
```css
.class {
  font-family: otherFont !important;
}
```

but alas, this did not help either. A little later, I noticed that not only the fonts are changing, but also the positioning of the elements and so on. It is worth commenting out the import of styles:

```js
// import "vue-pro-calendar/style";
```

and then all the problems disappear, as well as the styles for the calendar =( After looking at the styles that we import a little bit, I noticed that tailwind styles are used there as well as on my site, perhaps some of them differ from the original, so maybe that was the cause of this problem.

I also tried to create my own styles based on those that were originally there, cutting out some styles from there, everything fell into place except the calendar.. He broke down :D

**Comment by lbgm** [comment]
Hi @man0so1 , thank to you for opening this issue;

**Comment by lbgm** [comment]
Hi @man0so1 , thank you for opening this issue.

**Comment by lbgm** [comment]
Hi @man0so1, which version of tailwind do you use in your project ? be aware that the lib uses `"tailwindcss": "^3.2.2",` and doesn't modify any classes of. 

check this file https://github.com/lbgm/vue-pro-calendar/blob/main/tailwind.config.js.

Thanks.

**Comment by man0so1** [comment]
hello! my project uses `"tailwindcss": "^3.2.1"`. there doesn't seem to be a problem with the font anymore. one of the main problems was with the elements in the header. their adaptation was breaking down. going to the calendar page, a hidden element appeared and changed all the positioning in the header.

```js
screens: {
      mobile: { max: "767px" },
      large: { min: "768px" },
    },
```

could this be the cause of the problem?

**Comment by lbgm** [comment]
The calendar view is designed to utilize the screen size. Feel free to fork the code and modify it to suit your needs. At the moment, adaptations for smaller screens have not been made.
